### ISSUE TITLE
Skin display

### ISSUE THREAD

**Issue by xiaobao4909** [CapeCraft/TAB#6]
### Server version

Velocity 3.2.0-SNAPSHOT #252

### TAB version

3.3.1

### Describe the bug

Skin is the default skin for all services

### Expected behavior

Normal display of all skin

### Steps to reproduce

1. Install this plugin

### Additional info

I installed SkinRestorer

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by james090500** [comment]
This fork is closed due to upstream having velocity support ish
